[workspace]
members = ["crates/plugin_api","crates/uwu","crates/example_plugin"]
resolver = "3"

[patch.crates-io]
puffin = { git = "https://github.com/EmbarkStudios/puffin" }      # crates.io version uses out-of-date egui
puffin_egui = { git = "https://github.com/EmbarkStudios/puffin" } # crates.io version uses out-of-date egui

[profile.release]
strip = true
debug = 0
