[package]
name = "uwu"
description = "A powerful digital whiteboard built with Rust, winit, egui, and wgpu."
version = "0.5.0"
authors = ["Fey Xie <feyxiexzf@gmail.com>"]
edition = "2024"
repository = "https://github.com/Ujhhgtg/uwu/"
license-file = "LICENSE"

[features]
default = ["system_font"]
embedded_font = []
system_font = ["fontdb"]
profiling = ["dep:profiling", "puffin", "puffin_egui", "embedded_font"]
mimalloc = ["dep:mimalloc"]

[dependencies]
# ui & render
egui = { version = "0.34", default-features = false, features = [
    "serde",
    "rayon",
] }
egui-winit = { version = "0.34", default-features = false }
winit = { version = "0.30", default-features = false }
egui-wgpu = { version = "0.34", features = ["winit"] }
wgpu = { version = "29", default-features = false, features = [
    "dx12",
    "metal",
    "parking_lot",
    "serde",
    "std",
    "vulkan",
    "wgsl",
] }

# ui utils
egui-notify = "0.22"
image = { version = "0.25", default-features = false, features = [
    "ico",
    "jpeg",
    "png",
    "webp",
    "rayon",
] }
ttf-parser = "0.25"
rfd = "0.17"
printpdf = { version = "0.9", features = ["images"] }


# serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bitcode = "0.6"

# utils
dirs = "6"
interprocess = "2"
libloading = "0.8"
pollster = "0.4"
plugin_api = { path = "../plugin_api" }

# features dependencies
fontdb = { version = "0.23", optional = true }
profiling = { version = "1", optional = true, features = [
    "profile-with-puffin",
] }
puffin = { version = "0.20", optional = true }
puffin_egui = { version = "0.30", optional = true }
mimalloc = { version = "0.1", optional = true }

[build-dependencies]
winres = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
glib = { version = "0.22", default-features = false }
egui-winit = { version = "0.34", default-features = false, features = [
    "wayland",
] }
winit = { version = "0.30", default-features = false, features = ["wayland"] }
egui-wgpu = { version = "0.34", features = ["wayland"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_System_Console",
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = { version = "0.62", default-features = false }
winreg = "0.56"
